[tool.poetry]
name = "edgelist-converter"
version = "0.1.0"
description = "Convert an edgelist file into a more compact format"
authors = ["Simone Primarosa <simonepri@outlook.com>"]
license = "MIT"

[tool.taskipy.tasks]
lint = "python -m pylint src --max-line-length 80 -v --output-format colorized --disable duplicate-code,bad-continuation,too-many-locals,too-many-arguments"
types = "python -m mypy src"
format = "python -m black src --line-length 80"
test = "env PYTHONPATH=src python -m pytest tests"
bin = "env PYTHONPATH=src python"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.4.4"
pytest = "^5.4.1"
taskipy = "^1.2.0"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
